### PR TITLE
Allow the use of binding specifications in Redex languages.

### PR DESCRIPTION
**Pull request by paulstansifer**
Now, without the missing documentation

### CODE REVIEW

**Comment by paulstansifer** [comment]
...but it's still missing some files: Fixed in #12.

**Comment by samth** [comment]
Just so you know, if you push more commits to the branch for the pull
request, it will automatically update and you don't have to create a new
one.

**Comment by paulstansifer** [comment]
Yeah, it just felt silly to append a quick bugfix commit to a commit that was already 66 commits squashed together.

**Comment by samth** [comment]
You can rebase and then force-push to avoid the extra commit.

**Pull request closed without merging**
