### PR TITLE
reuse some standard functions; eliminate multiple passes in a few places

### PR DESCRIPTION
**Pull request by philnguyen**
This commit attempts to clean up and micro-optimize some by:
* reusing library functions where possible (e.g. `dropf-right`, `hash-update!`, `hash-ref!`)
* avoiding repeatedly calling linear-time functions (e.g. `length`, `list-ref`)

### CODE REVIEW

**Comment by rfindler** [comment]
Are these changes covered by the existing test suites?

**Comment by philnguyen** [comment]
Not that I'm aware of :D. I did a search for `search/next` and it didn't seem to be directly tested. Are functions in this module indirectly tested by tests on judgment-form-based random generation? I can try adding some tests if there are guidelines about how these functions with random behaviors are tested.

Otherwise it's not really important. I was just interested in how this thing is tuned in practice and made some edits along the way to help myself understand.

**Comment by rfindler** [comment]
Thanks, @philnguyen. I'll look into testing the changes more carefully later on; they look good to me, but I wouldn't want to merge them without being able to rely on just our eyes looking at the code.

**Comment by rfindler** [comment]
Indeed, the existing test suites get to all of the functions that are changed.

Thanks!!

**Pull request merged**
