### PR TITLE
Remove dependency on `unstable-list-lib`

### PR DESCRIPTION
**Pull request by stamourv**
Depends on Racket PR #972, which moves most of its contents to core libraries.

### CODE REVIEW

**Comment by samth** [comment]
This needs a dependency on a new base version.

**Comment by stamourv** [comment]
That somehow slipped off my radar. Will push now.

**Comment by stamourv** [comment]
Actually, @rfindler, would it be better to wait until the end of the Redex summer school?

**Comment by rfindler** [comment]
Nah, go for it.

**Pull request merged**
