### PR TITLE
Add clarification about middle dot character

### PR DESCRIPTION
**Pull request by leafac**
I tripped on this when following the tutorial.

### CODE REVIEW

**Comment by rfindler** [comment]
How about changing it to another character that's more obvious, like a bigger • ? And also I'm not sure that those comments will render in the output?

**Comment by leafac** [comment]
You are correct, the comments don't render in the output.

But I don't think that replacing the middle dot with something else is such a good idea. It's not only used in this tutorial, but all over Redex.

I'd say it's better to educate the reader of the use of the middle dot, as proposed on the https://github.com/racket/redex/pull/59/commits/275f231a1758ad3c43dee3ea8399d13b038270c7 commit.

----

Since we're talking, I have two questions:

1. How do make DrRacket wrap lines? I tried using `M-q`—as in Emacs—, but then I don't know how long a line should be. And the document I'm editing in this Pull Request has shorter lines than the default.

2. Rendering the Scribble HTML is painfully slow. Almost a hole minute per render and the time isn't amortizing after a few builds. How do you handle that?

Thanks a lot!

**Comment by rfindler** [comment]
I don't mind if you want to change the dot in more places, but also using
"code:comment" is okay.

Scribble rendering takes time. There isn't any easy fix I know.

Please don't rewrap lines unless you are already editing most of them
because "git blame" is so useful. But yes, in drracket when editing
scribble files, esc;q (or alt-q) should work.

**Comment by leafac** [comment]
Thanks for the answers.

I don't plan to rewrap lines unless I'm changing most of them. I agree that `git blame` is useful. That's why I asked whether I was able to configure line length in DrRacket. I couldn't find that in the documentation.

------

Anyhow, coming back to the issue at hand, following is the list of places where the middle dot appears. Are you sure you are fine with me changing them all? I still think a simple explanation like the one I proposed before would suffice.

```
redex-benchmark/redex/benchmark/models/delim-cont/delim-cont-1.rkt
34:       (keymT : (→ Num Unit) (call/cm : Bool ·))))

redex-benchmark/redex/benchmark/models/delim-cont/delim-cont-2.rkt
25:       ·))

redex-benchmark/redex/benchmark/models/delim-cont/delim-cont-3.rkt
28:            (call/comp : (→ Num Bool) (call/comp : Num ·)))))

redex-benchmark/redex/benchmark/models/delim-cont/generators.rkt
44:            (tc · Σ e t)

redex-benchmark/redex/benchmark/models/delim-cont/delim-cont.rkt
14:  (σ · (key σ) (tag σ))
32:     ·)
95:  (Γ · (x : t Γ))
96:  (Σ · (v : t Σ))
243:   (--> (wcm (in-hole W ·)
245:        (wcm (in-hole W ((key v) ·))
252:        (<> (in-hole E (wcm · (call/cm v_1 v_2 e))) Σ)
257:        (<> (in-hole E (wcm · (call/comp v_1 v_2))) Σ)
332:  [(merge · w)
339:          (in-hole W ·))
341:          (in-hole W ((v_1 v_2) ·)))])
533:   (tc-w Γ Σ ·)]) 
540:  [(∈-Γ any ·) #f])
547:  [(∈-Σ any ·) #f])
747:   (where (in-hole W ·) w)
771:(define (abort-eval t #:init-store [store (term ·)])
835:       (tc · Σ e t)
838:    [`(tc · ,Σ ,e ,t) 
864:      (= (length (apply-reduction-relation abort-red `(<> ,e ·)))
868:  (define t (judgment-holds (tc · · ,e t) t))
871:      (match (apply-reduction-relation abort-red `(<> ,e ·))
873:         (equal? (judgment-holds (tc · ,st* ,e* t) t)
886:(define (soundness-holds? e [inp-Σ '·])
887:  (define t (judgment-holds (tc · ,inp-Σ ,e t) t))
907:                      (equal? (judgment-holds (tc · ,st* ,e* t) t)
927:  (judgment-holds (tc · ,Σ ,e t)))

redex-benchmark/redex/benchmark/models/delim-cont/test.rkt
12: (tc · · (+ 1 2) t)
15: (tc · · ((λ (var:x : Num) (+ var:x 5)) 3) t)
18: (tc · · (if (zero? 0) #t #f) t)
21: (tc · ·
31: (tc · · (flat (λ (x : Num) (zero? x))) t)
34: (tc ·
35:     (tag0 : (Prompt Num Num) ·)
49: (term (no-match (wcm ((key_0 0) ·) hole) tag_0))
52: (term (no-match (wcm · hole) tag_0))
85:                            #:init-store (term ·)
86:                            #:store-type ·)]
89:                     (check-true (judgment-holds (tc · ?store-type ,?input t)))
230:          (wcm ((key0 5) ·) (var:f unit)))
232:          (wcm ((key0 3) ·) (ccm key0 Num)))))
234: #:init-store (term (key0 : (Mark Num) ·))
235: #:store-type (key0 : (Mark Num) ·))
498:                  (wcm · hole)) tag))
520:  (no-match (call/cm key (wcm · hole) 
521:                     ((wcm · (λ (var:C : Bool) #f)) (unit? 3))) 
542:   ·
554:      ·)))
559:     ·
570:   ·
580:      (key : (Mark (Prompt Unit (Mark (List (Mark Unit))))) ·))))
592:     ·)
605:  (tc · (key : (Mark (Mark (Mark Num))) ·)
619:(check-false (term (not-wcm (wcm · hole))))
620:(check-false (term (not-wcm (+ 5 (wcm · hole)))))

redex-benchmark/redex/benchmark/models/let-poly/generators.rkt
50:         (let loop ([Σ+M `(· ,M)] [n 100])

redex-doc/redex/scribblings/extended-exercises/contract.rkt
14:     (c · e x x) ;; monitor a contract
23:(define a-module (term {(even? -> pos?) · (lambda (x) (+ x 1)) server client}))
33:                             {(even? -> pos?) · (lambda (x) (+ x 1))
48:     (c · E x x)))
65:   (--> (in-hole E (pos? · n x_s x_c))
68:   (--> (in-hole E (even? · n x_s x_c))
71:   (--> (in-hole E (odd? · n x_s x_c))
74:   (--> (in-hole E (num? · n x_s x_c))
77:   (--> (in-hole E ((c_1 -> c_2) · (lambda (x) e) x_s x_c))
80:                   (c_2 · ((lambda (x) e) (c_1 · x x_c x_s)) x_s x_c))))

redex-doc/redex/scribblings/extended-exercises/extended-exercises.scrbl
319:     (c · e x x)
333:The contract form @racket[(c · e x_s x_c)] checks contract @racket[_c] on
344:(define a-module (term {(even? -> pos?) · (lambda (x) (+ x 1)) server client}))

redex-doc/redex/scribblings/ref/typesetting.scrbl
111:       (K · (1 K) (0 K)))
112:     (render-term nums (+ (1 (0 (1 ·))) (+ (1 (1 (1 ·))) (1 (0 (0 ·))))))]
116: @ex[(let ([x (term (+ (1 (1 (1 ·))) (1 (0 (0 ·)))))])
290:      [(add K ·) K]
291:      [(add · K) K]
295:      [(add (1 K_1) (1 K_2)) (0 (add (1 ·) (add K_1 K_2)))])
322:       [(to-nat ·) 0]
328: @ex-tests[(test-equal (term (to-nat (0 (0 (0 ·))))) 0)
329:           (test-equal (term (to-nat (0 (0 (1 ·))))) 4)
330:           (test-equal (term (to-nat (0 (1 (1 ·))))) 6)
331:           (test-equal (term (to-nat (1 (1 (1 ·))))) 7)
332:           (test-equal (term (to-nat (1 (1 (0 ·))))) 3)
333:           (test-equal (term (to-nat (1 (0 (1 ·))))) 5)
362:       [--------- eq-·
363:        (eq · ·)]
365:       [(eq K ·)
367:        (eq (0 K) ·)]
369:       [(eq · K)
371:        (eq · (0 K))]
381:     (parameterize ([judgment-form-cases '("eq-·")])
885:        ·
890:        (where (1 ·) K_5)]
891:       [(f K) (0 ·)])
901: @ex-tests[(test-equal (term (f ·)) (term (0 ·)))
902:           (test-equal (term (f (0 (1 (0 (1 (1 ·))))))) (term ·))

redex-doc/redex/scribblings/tut.scrbl
300:by letting the middle dot @tt{·}---not to be confused with a
305:            [Γ · (x : t Γ)])]
394:@amb-try[(test-equal (judgment-holds (types (x : num ·) y t_1) t_1)
396:         (test-equal (judgment-holds (types (x : num ·) x t_1) t_1)
398:         (test-equal (judgment-holds (types (x : num (y : (→ num num) ·)) x t_1) t_1)
400:         (test-equal (judgment-holds (types (x : num (y : (→ num num) ·)) y t_1) t_1)
402:         (test-equal (judgment-holds (types (x : num (x : (→ num num) ·)) y t_1) t_1)
404:         (test-equal (judgment-holds (types · (+ 1 2 3) t_1) t_1)
406:         (test-equal (judgment-holds (types · (λ (y num) y) t_1) t_1)
408:         (test-equal (judgment-holds (types · (λ (y num) (λ (z num) z)) t_1) t_1)
410:         (test-equal (judgment-holds (types · (λ (y num) (λ (z num) y)) t_1) t_1)
412:         (test-equal (judgment-holds (types · (λ (y num) (λ (z num) q)) t_1) t_1)
414:         (test-equal (judgment-holds (types · (((λ (x num) (λ (y num) x)) 1) 2) t_1) t_1)
416:         (test-equal (judgment-holds (types · (amb) t_1) t_1)
418:         (test-equal (judgment-holds (types · (amb 1) t_1) t_1)
420:         (test-equal (judgment-holds (types · (amb 1 2) t_1) t_1)
422:         (test-equal (judgment-holds (types · (+ (amb (+ 1 2) (+ 3 4.5))
436:                   (types ·
464:                   (types ·
488:            (types · (λ (x num) x) t)
493:            (types · (amb 1 2 3) t)
498:            (types · (+ 1 2) t)
914:            (not (null? (judgment-holds (types · ,e t)
1011:                   (define tys (judgment-holds (types · ,e t) t))
1017:                          (define next-tys (judgment-holds (types · ,next-e t) t))

redex-examples/redex/examples/lazy-with-binding.rkt
27:  (Γ Δ Θ ::= · (Γ x ↦ e))
78:  [(separate · x) ⊥]
102:  (define vs (judgment-holds (⇓ · ,p Δ v) v))
115:    (⇓ · ,p Δ v))))
123:  (test-equal (term (separate · x)) (term ⊥))
124:  (test-equal (term (separate (· x ↦ 1) x)) (term (· x ↦ 1)))
125:  (test-equal (term (separate ((· x ↦ 1) y ↦ 2) x))
126:                (term ((· y ↦ 2) x ↦ 1)))
127:  (test-equal (term (separate (· x ↦ 1) y)) (term ⊥))
131:  (test-equal (judgment-holds (⇓ (· y ↦ 1) ((λ (x) x) y) Δ v) v)

redex-examples/redex/examples/lazy.rkt
27:  (Γ Δ Θ ::= · (Γ x ↦ e)))
74:  [(separate · x) ⊥]
228:  (define vs (judgment-holds (⇓ · ,p Δ v) v))
241:    (⇓ · ,p Δ v))))
278:  (test-equal (term (separate · x)) (term ⊥))
279:  (test-equal (term (separate (· x ↦ 1) x)) (term (· x ↦ 1)))
280:  (test-equal (term (separate ((· x ↦ 1) y ↦ 2) x)) 
281:              (term ((· y ↦ 2) x ↦ 1)))
282:  (test-equal (term (separate (· x ↦ 1) y)) (term ⊥))
284:  (test-equal (term (^ (· x ↦ (λ (x) x)) (λ (x) x))) 
286:  (test-equal (term (^ · (λ (x) (λ (y) (x y))))) 
288:  (test-equal (term (^ (· x ↦ y) (let ([x 1] [y 2]) x)))
290:  (test-equal (term (^ (· x ↦ x1) (λ (x) (+ x y))))
292:  (test-equal (term (^ (· tri ↦ (λ (x) (let ((x1 x)) x1)))
295:  (test-equal (term (^ (· x ↦ 1)
302:  (test-equal (term (^ (· x ↦ 1)
306:  (test-equal (judgment-holds (⇓ (· y ↦ 1) ((λ (x) x) y) Δ v) v)

redex-examples/redex/examples/let-poly.rkt
21:     ·)
44:  (Σ ::= · (r v Σ))
47:     · 
52:  (G  ::= · (τ σ G))
53:  (Gx ::= · (x σ Gx)))
81:  [(tc-down · M · σ)
128:   (tc-up σ_ans · σ_ans)]
165:  [(lookup-Γ · x) #f])
169:  [(unify τ σ) (uh (τ σ ·) ·)])
185:  [(uh · Gx) Gx]
211:  [(eliminate-G x τ ·) ·]
245:  [(apply-subst-τ · τ) τ]
251:  [(apply-subst-κ Gx ·) ·]
263:  [(apply-subst-Γ Gx ·) ·])
386:  (define res (apply-reduction-relation* red (term (· ,M))))
415:(define/contract (type-check M [Σ (term ·)])
435:      [`· (void)]
545:  (test-equal (Σ+M->M (term (r1 r2 (r2 1 ·))) (term 2))
547:  (test-equal (Σ+M->M (term (r2 1 (r1 r2 ·))) (term 2))
590:              (term (x int ·)))
592:              (term (x int ·)))
596:              (term ·))
598:              (term ·))
600:              (term (x (list int) (y int ·))))
608:              (term (z int (y (list int) (x int ·)))))
611:              (term (z int (y (list int) (x int ·)))))
614:              (term (z int (y int (x int ·)))))
663:  (test-->> red (term (· ((λ x x) 7))) (term (· 7)))
664:  (test-->> red (term (· (((λ x (λ x x)) 2) 1))) (term (· 1)))
665:  (test-->> red (term (· (((λ x (λ y x)) 2) 1))) (term (· 2)))
667:            (term (· ((λ x ((cons x) nil)) 11)))
668:            (term (· ((cons 11) nil))))
670:            (term (· ((λ x ((cons x) nil)) 11)))
671:            (term (· ((cons 11) nil))))
673:            (term (· ((cons ((λ x x) 11)) nil)))
674:            (term (· ((cons 11) nil))))
676:            (term (· (cons ((λ x x) 1))))
677:            (term (· (cons 1))))
679:            (term (· ((cons ((λ x x) 1)) nil)))
680:            (term (· ((cons 1) nil))))
682:            (term (· (hd ((λ x ((cons x) nil)) 11))))
683:            (term (· 11)))
685:            (term (· (tl ((λ x ((cons x) nil)) 11))))
686:            (term (· nil)))
688:            (term (· (tl nil)))
691:            (term (· (hd nil)))
694:            (term (· ((+ 1) (hd nil))))
697:            (term (· ((+ ((+ 1) 2)) ((+ 3) 4))))
698:            (term (· 10)))
700:            (term (· ((λ f (f 3)) (cons 1))))
701:            (term (· ((cons 1) 3))))
703:            (term (· ((λ f (f 3)) (+ 1))))
704:            (term (· 4)))
706:            (term (· (let ([f (+ 2)]) ((+ (f 3)) (f 4)))))
707:            (term (· 11)))
709:            (term (· (get (new 1))))
710:            (term ((r 1 ·) 1)))
712:            (term (· ((set (new 1)) 2)))
713:            (term ((r 2 ·) 1)))
716:            (term (· (let ([r (new 1)])
719:            (term ((r 2 ·) 2)))
722:            (term (· (let ([r (new nil)])
725:            (term ((r ((cons 5) nil) ·) (5 1))))
739:  (test-equal (type-check (term r1) (term (r1 r (r 1 ·))))
741:  (test-equal (type-check (term r1) (term (r 1 (r1 r ·))))

redex-examples/redex/examples/stlc.rkt
21:  (Γ · (x τ Γ)))
112:  [(lookup · x) #f])
128:(generate-term λv #:satisfying (typeof · e num) 5)
132:  (define types (judgment-holds (typeof · ,e τ) τ))
139:       (equal? (judgment-holds (typeof · ,v τ) τ)
144:               #:satisfying (typeof · e num) 
198:(test-equal (typecheck (term ·) (term 1))
200:(test-equal (typecheck (term ·) (term (1 1)))
202:(test-equal (typecheck (term (x num ·)) (term x))
204:(test-equal (typecheck (term ·) (term x))
206:(test-equal (typecheck (term ·) (term ((λ (x num) x) 1)))
208:(test-equal (typecheck (term ·) (term (((λ (x num) x) 1) 2)))
210:(test-equal (typecheck (term ·) 
217:(test-equal (typecheck (term ·)
224:(test-equal (typecheck (term ·) (term (+ (+ 1 2) 3)))
226:(test-equal (typecheck (term ·) (term (if0 1 (λ (x num) x) 3)))
228:(test-equal (typecheck (term ·) (term (if0 1 2 3)))
230:(test-equal (typecheck (term ·) (term (λ (x num) (x 2))))
232:(test-equal (typecheck (term ·)
237:(test-equal (typecheck (term ·)
```

**Comment by rfindler** [comment]
A simple explanation seems okay to me too. I think if you write

(code:comment "a simple explanation")

in the place where you put the semicolons, you'd see the simple explanation show up.

FWIW, I thinking only of the docs, but I agree there are a lot of places!

**Comment by leafac** [comment]
Do you prefer the `code:comment` option over the proposal in [this commit](https://github.com/racket/redex/pull/59/commits/275f231a1758ad3c43dee3ea8399d13b038270c7)? I like the proposed version better, that's why I'm asking, but I can go either way according to your preference.

-----

Again on an slight off-topic, is there a better solution to [Exercise 6](http://docs.racket-lang.org/redex/tutorial.html) than _escaping back_ to Racket—or, equivalently, defining a metafunction?

```
[(types-exercise-6 Γ e t_2) ...
 (side-condition ,(andmap (curry equal? (term t_1)) (term (t_2 ...))))
 -------------------------
 (types-exercise-6 Γ (amb t_1 e ...) t_1)]
```

Thanks a lot!

**Comment by rfindler** [comment]
I'm happy with that option, sure.

As for the exercise, I had intended that just writing t_1 everywhere (with
no side-condition line) should have worked, but I see that it produces this
error:

define-judgment-form: found the same binder, t_1, at different depths, 1
and 0

I'm not positive, but I think this is best considered a bug in Redex. (The
ellipsis that appears outside of the premises is handled differently than
the one that lives inside a particular premise and this demonstrates
too-naive handling, I believe.)

**Comment by leafac** [comment]
> I'm happy with that option, sure.

Great, thanks for reviewing. Is there anything else you want me to do before you can merge my Pull Request?

As for Exercise 6: I forgot to mention, but using `t_1` was my first approach as well. I think it is the natural first guess.

I'd like to explore this a bit further and help you figure out if it should be considered a bug in Redex or not. I think it would be a nice way to get my feet wet in Redex. But, right now, I'm not sure how to proceed. For example, what do you mean by _the ellipses are handled differently_? How is each one being handled?

Or, more specifically, how can I help?

**Comment by rfindler** [comment]
I'm pretty sure it should be considered a bug, but it's less clear to me how to fix it.

Here's the issue: In general, this aspect of the handling of ellipses is implemented by the racket/datum library (the same library that syntax-case uses). It can cope with writing things like this:

```
  ((a b) ...)
```

where `a` is bound in some pattern like this `(a ...)` but `b` is just `b` with no ellipsis around it. It handles this by duplicating `b`, once for each `a`. That's what we'd like to happen here too. But the ellipses that are "between" premises in a `define-judgment-form` are not handled by just giving them to the racket/datum library. Instead, Redex is doing some of its own work before it can hand them off. And that work is what is raising the syntax error in this case. 

So: best case, we figure out a more relaxed well-formedness check to implement in `define-judgment-form` and this example just starts working. Worse case, we need to change how the "inter premise" ellipses handling is implemented. I'm not sure which case we are in.

Also, we need a small(ish) test case. Here's one:

```
#lang racket
(require redex/reduction-semantics)

(define-language L
  (τ ::= n b)
  (e ::= (amb τ e ...) natural #t #f))

(define-judgment-form L
  #:mode (type I O)
  [----------------
   (type natural n)]

  [-----------
   (type #t b)]

  [-----------
   (type #f b)]

  [(type e τ) ...
   ----------------------
   (type (amb τ e ...) τ)])

(test-judgment-holds (type (amb b #f #t) b))
(test-judgment-holds (type (amb n 0 1) n))
(test-equal (judgment-holds (type (amb n 0 #f) any)) #f)
(test-equal (judgment-holds (type (amb n #t #t 11 #f) any)) #f)
```

**Comment by leafac** [comment]
Thanks for merging the Pull Request.

And thanks for the careful and thoughtful explanation of the problem. I can confirm that the test case you provided triggers the same `found the same binder, [...], at different depths` error as I had before.

I'll now take a deeper look into well-formedness check of `define-judgment-form` and `racket/datum`—which is new to me. For now, I [created an issue](https://github.com/racket/redex/issues/61) to continue the conversation.

**Pull request merged**
